[project]
name = "joint_test"
version = "0.0.0"
license = "GPL-3.0"
edition = "2018"

[dependencies]

nphysics3d = "0.13.0"
ncollide3d = "0.21.0"
nalgebra = "0.19.0"
gnuplot = "0.0.32"

[[bin]]
name = "joint_test"
path = "main.rs"
